// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEDeLsFkLI_JKUrB6e62aM5kMwQwFps_g',
    appId: '1:117656281108:web:5f64ab09e09aa1493e8701',
    messagingSenderId: '117656281108',
    projectId: 'appdeliverypuce',
    authDomain: 'appdeliverypuce.firebaseapp.com',
    storageBucket: 'appdeliverypuce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtRujHZH2AOh1z4ADgT7u18sVQW00XGy4',
    appId: '1:117656281108:android:5fc58126a11ceb273e8701',
    messagingSenderId: '117656281108',
    projectId: 'appdeliverypuce',
    storageBucket: 'appdeliverypuce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAothONXt3B4Rsc1EcmVgv1cmAmiHdxYHs',
    appId: '1:117656281108:ios:8372bc475982b1ed3e8701',
    messagingSenderId: '117656281108',
    projectId: 'appdeliverypuce',
    storageBucket: 'appdeliverypuce.firebasestorage.app',
    iosBundleId: 'com.example.puceDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAothONXt3B4Rsc1EcmVgv1cmAmiHdxYHs',
    appId: '1:117656281108:ios:8372bc475982b1ed3e8701',
    messagingSenderId: '117656281108',
    projectId: 'appdeliverypuce',
    storageBucket: 'appdeliverypuce.firebasestorage.app',
    iosBundleId: 'com.example.puceDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEDeLsFkLI_JKUrB6e62aM5kMwQwFps_g',
    appId: '1:117656281108:web:b4ba36727f69d16d3e8701',
    messagingSenderId: '117656281108',
    projectId: 'appdeliverypuce',
    authDomain: 'appdeliverypuce.firebaseapp.com',
    storageBucket: 'appdeliverypuce.firebasestorage.app',
  );
}
